[package]
name = "suzaku-cli"
version = "0.1.0"
authors = ["xpw-osr <x1npen9w@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1", features = ["derive"]}
core = {path = '../core'}